-- MySQL Script generated by MySQL Workbench
-- dom 28 ene 2018 15:51:51 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Lobos_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Lobos_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Lobos_db` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `Lobos_db` ;

-- -----------------------------------------------------
-- Table `Lobos_db`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lobos_db`.`Users` (
  `matricula` VARCHAR(10) NOT NULL,
  `name` VARCHAR(20) NULL,
  `lastname` VARCHAR(20) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `career` VARCHAR(3) NULL,
  `grade` INT(11) NULL,
  `group` CHAR(1) NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lobos_db`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lobos_db`.`Questions` (
  `idQuestions` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(45) NULL,
  `question_description` VARCHAR(200) NULL,
  `user_matricula` VARCHAR(10) NOT NULL,
  `date` TIMESTAMP NULL DEFAULT now(),
  PRIMARY KEY (`idQuestions`),
  INDEX `fk_Questions_Personas_idx` (`user_matricula` ASC),
  CONSTRAINT `fk_Questions_Personas`
    FOREIGN KEY (`user_matricula`)
    REFERENCES `Lobos_db`.`Users` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lobos_db`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lobos_db`.`Answer` (
  `idAnswer` INT NOT NULL,
  `answer` VARCHAR(500) NULL,
  PRIMARY KEY (`idAnswer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lobos_db`.`Questions_has_Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lobos_db`.`Questions_has_Answer` (
  `Questions_idQuestions` INT NOT NULL,
  `Answer_idAnswer` INT NOT NULL,
  `user_matricula` VARCHAR(10) NULL,
  PRIMARY KEY (`Questions_idQuestions`, `Answer_idAnswer`),
  INDEX `fk_Questions_has_Answer_Answer1_idx` (`Answer_idAnswer` ASC),
  INDEX `fk_Questions_has_Answer_Questions1_idx` (`Questions_idQuestions` ASC),
  CONSTRAINT `fk_Questions_has_Answer_Questions1`
    FOREIGN KEY (`Questions_idQuestions`)
    REFERENCES `Lobos_db`.`Questions` (`idQuestions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questions_has_Answer_Answer1`
    FOREIGN KEY (`Answer_idAnswer`)
    REFERENCES `Lobos_db`.`Answer` (`idAnswer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
